import React from "react"
import { Line } from "react-chartjs-2"
import { Container } from "react-bootstrap"
import {RIT, MINECRAFT, 
  BITCOIN, WALLSTREET,
ROBINHOOD, GAMESTOP, PLAYSTATION,
XBOX, NINTENDO, TWITCH} from './BrandColors'

class LineChart extends React.Component {
  state = {
    dataLine: {
      labels: ["Day 05", "Day 10", "Day 15", "day 20", "day 25", "Day 30"],
      datasets: [
        {
          label: "rit",
          fill: false,
          lineTension: 0.3,
          backgroundColor: "rgba(247, 105, 2, .3)",
          borderColor: RIT.PRIMARY,
          borderCapStyle: "butt",
          borderDash: [],
          borderDashOffset: 0.0,
          borderJoinStyle: "miter",
          pointBorderColor: RIT.PRIMARY,
          pointBackgroundColor: RIT.PRIMARY,
          pointBorderWidth: 10,
          pointHoverRadius: 5,
          pointHoverBackgroundColor: "rgb(0, 0, 0)",
          pointHoverBorderColor: "rgba(220, 220, 220, 1)",
          pointHoverBorderWidth: 2,
          pointRadius: 1,
          pointHitRadius: 10,
          data: [65, 59, Math.random(), 81, 56, 55]
        },
        {
          label: "minecraft",
          fill: false,
          lineTension: 0.3,
          backgroundColor: "rgba(	2, 138, 15, .3)",
          borderColor: MINECRAFT.PRIMARY,
          borderCapStyle: "butt",
          borderDash: [],
          borderDashOffset: 0.0,
          borderJoinStyle: "miter",
          pointBorderColor: MINECRAFT.PRIMARY,
          pointBackgroundColor: MINECRAFT.PRIMARY,
          pointBorderWidth: 10,
          pointHoverRadius: 5,
          pointHoverBackgroundColor: "rgb(0, 0, 0)",
          pointHoverBorderColor: "rgba(220, 220, 220, 1)",
          pointHoverBorderWidth: 2,
          pointRadius: 1,
          pointHitRadius: 10,
          data: [Math.random(), 48, 40, 19, 86, 27]
        },
        {
          label: "bitcoin",
          fill: false,
          lineTension: 0.3,
          backgroundColor: "rgba(	2, 138, 15, .3)",
          borderColor: BITCOIN.PRIMARY,
          borderCapStyle: "butt",
          borderDash: [],
          borderDashOffset: 0.0,
          borderJoinStyle: "miter",
          pointBorderColor: BITCOIN.PRIMARY,
          pointBackgroundColor: BITCOIN.PRIMARY,
          pointBorderWidth: 10,
          pointHoverRadius: 5,
          pointHoverBackgroundColor: "rgb(0, 0, 0)",
          pointHoverBorderColor: "rgba(220, 220, 220, 1)",
          pointHoverBorderWidth: 2,
          pointRadius: 1,
          pointHitRadius: 10,
          data: [28, 48, 40, Math.random(), 86, 27]
        },
        {
          label: "wallstreetbets",
          fill: false,
          lineTension: 0.3,
          backgroundColor: "rgba(	2, 138, 15, .3)",
          borderColor: WALLSTREET.PRIMARY,
          borderCapStyle: "butt",
          borderDash: [],
          borderDashOffset: 0.0,
          borderJoinStyle: "miter",
          pointBorderColor: WALLSTREET.PRIMARY,
          pointBackgroundColor: WALLSTREET.PRIMARY,
          pointBorderWidth: 10,
          pointHoverRadius: 5,
          pointHoverBackgroundColor: "rgb(0, 0, 0)",
          pointHoverBorderColor: "rgba(220, 220, 220, 1)",
          pointHoverBorderWidth: 2,
          pointRadius: 1,
          pointHitRadius: 10,
          data: [28, 48, 40, 19, Math.random(), 27]
        },
        {
          label: "robinhood",
          fill: false,
          lineTension: 0.3,
          backgroundColor: "rgba(	2, 138, 15, .3)",
          borderColor: ROBINHOOD.PRIMARY,
          borderCapStyle: "butt",
          borderDash: [],
          borderDashOffset: 0.0,
          borderJoinStyle: "miter",
          pointBorderColor: ROBINHOOD.PRIMARY,
          pointBackgroundColor: ROBINHOOD.PRIMARY,
          pointBorderWidth: 10,
          pointHoverRadius: 5,
          pointHoverBackgroundColor: "rgb(0, 0, 0)",
          pointHoverBorderColor: "rgba(220, 220, 220, 1)",
          pointHoverBorderWidth: 2,
          pointRadius: 1,
          pointHitRadius: 10,
          data: [28, 48, 40, 19, 86, Math.random()]
        },
        {
          label: "gamestop",
          fill: false,
          lineTension: 0.3,
          backgroundColor: "rgba(	2, 138, 15, .3)",
          borderColor: GAMESTOP.PRIMARY,
          borderCapStyle: "butt",
          borderDash: [],
          borderDashOffset: 0.0,
          borderJoinStyle: "miter",
          pointBorderColor: GAMESTOP.PRIMARY,
          pointBackgroundColor: GAMESTOP.PRIMARY,
          pointBorderWidth: 10,
          pointHoverRadius: 5,
          pointHoverBackgroundColor: "rgb(0, 0, 0)",
          pointHoverBorderColor: "rgba(220, 220, 220, 1)",
          pointHoverBorderWidth: 2,
          pointRadius: 1,
          pointHitRadius: 10,
          data: [Math.random(), 48, 40, 19, 86, 27]
        },
        {
          label: "playstation",
          fill: false,
          lineTension: 0.3,
          backgroundColor: "rgba(	2, 138, 15, .3)",
          borderColor: PLAYSTATION.PRIMARY,
          borderCapStyle: "butt",
          borderDash: [],
          borderDashOffset: 0.0,
          borderJoinStyle: "miter",
          pointBorderColor: PLAYSTATION.PRIMARY,
          pointBackgroundColor: PLAYSTATION.PRIMARY,
          pointBorderWidth: 10,
          pointHoverRadius: 5,
          pointHoverBackgroundColor: "rgb(0, 0, 0)",
          pointHoverBorderColor: "rgba(220, 220, 220, 1)",
          pointHoverBorderWidth: 2,
          pointRadius: 1,
          pointHitRadius: 10,
          data: [28, Math.random(), 40, 19, 86, 27]
        },
        {
          label: "xbox",
          fill: false,
          lineTension: 0.3,
          backgroundColor: "rgba(	2, 138, 15, .3)",
          borderColor: XBOX.PRIMARY,
          borderCapStyle: "butt",
          borderDash: [],
          borderDashOffset: 0.0,
          borderJoinStyle: "miter",
          pointBorderColor: XBOX.PRIMARY,
          pointBackgroundColor: XBOX.PRIMARY,
          pointBorderWidth: 10,
          pointHoverRadius: 5,
          pointHoverBackgroundColor: "rgb(0, 0, 0)",
          pointHoverBorderColor: "rgba(220, 220, 220, 1)",
          pointHoverBorderWidth: 2,
          pointRadius: 1,
          pointHitRadius: 10,
          data: [28, 48, 40, Math.random(), 86, 27]
        },
        {
          label: "nintendo",
          fill: false,
          lineTension: 0.3,
          backgroundColor: "rgba(	2, 138, 15, .3)",
          borderColor: NINTENDO.PRIMARY,
          borderCapStyle: "butt",
          borderDash: [],
          borderDashOffset: 0.0,
          borderJoinStyle: "miter",
          pointBorderColor: NINTENDO.PRIMARY,
          pointBackgroundColor: NINTENDO.PRIMARY,
          pointBorderWidth: 10,
          pointHoverRadius: 5,
          pointHoverBackgroundColor: "rgb(0, 0, 0)",
          pointHoverBorderColor: "rgba(220, 220, 220, 1)",
          pointHoverBorderWidth: 2,
          pointRadius: 1,
          pointHitRadius: 10,
          data: [28, 48, 40, 19, Math.random(), 27]
        },
        {
          label: "twitch",
          fill: false,
          lineTension: 0.3,
          backgroundColor: "rgba(	2, 138, 15, .3)",
          borderColor: TWITCH.PRIMARY,
          borderCapStyle: "butt",
          borderDash: [],
          borderDashOffset: 0.0,
          borderJoinStyle: "miter",
          pointBorderColor: TWITCH.PRIMARY,
          pointBackgroundColor: TWITCH.PRIMARY,
          pointBorderWidth: 10,
          pointHoverRadius: 5,
          pointHoverBackgroundColor: "rgb(0, 0, 0)",
          pointHoverBorderColor: "rgba(220, 220, 220, 1)",
          pointHoverBorderWidth: 2,
          pointRadius: 1,
          pointHitRadius: 10,
          data: [Math.random(), 48, Math.random(), 19, 86, 34]
        }
      ]
    }
  };

  render() {
    return (
      <Container>
        <h3 className="mt-5">Line chart</h3>
        <Line data={this.state.dataLine} options={{ responsive: true }} />
      </Container>
    );
  }
}

export default LineChart;